services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - .:/app  # Mount the current directory (.) to /app in the container