apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stock-app-backend-config
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    port: 8000
    requestPath: /