replicaCount: 2

image:
  repository: gcr.io/sto-yah/stock-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "stock-app-ip"
  hosts:
    - host: stoyah.work.gd
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"